In [1]:
import numpy as np

In [139]:
y_true = np.array(
    [10, 10, 0, 0, -1, -3] #0.5, 0.2
)

y_pred = np.array(
    [0, 11, 10, 0, -0.5, 2.5] # 50, 20
)

In [140]:
# exclude when in divider two zeros


def smape(y_true: np.array, y_pred: np.array) -> float:
    """Description of function."""
    return np.mean(np.abs(y_pred - y_true) * 2 / (np.abs(y_pred) + np.abs(y_true)))


print(smape(y_true, y_pred))

nan


/var/folders/2g/vm02gnkd7nd3lzt5qcby6t7r0000gn/T/ipykernel_17165/4290492041.py:6: RuntimeWarning: invalid value encountered in divide
  return np.mean(np.abs(y_pred - y_true) * 2 / (np.abs(y_pred) + np.abs(y_true)))


In [141]:
# exclude when in divider two zeros


def smape(y_true: np.array, y_pred: np.array) -> float:
    """Description of function."""
    return np.mean(
        np.abs(y_pred - y_true) * 2 / 
        np.where(
            (np.abs(y_pred) + np.abs(y_true)) == 0, 
            0.0001, 
            np.abs(y_pred) + np.abs(y_true))
)


print(smape(y_true, y_pred))

1.126984126984127


In [131]:
np.where((np.abs(y_pred) + np.abs(y_true)) == 0, 0.01, np.abs(y_pred) + np.abs(y_true))




array([1.0e+01, 2.1e+01, 1.0e+01, 1.0e-02])

In [116]:
y_true == 0

array([False, False,  True,  True])

In [118]:
y_true[y_true == 0]

array([0, 0])

In [117]:
y_pred == 0

array([ True, False, False,  True])

In [124]:
# mask with conditions boolean


mask = ((y_true == 0) & (y_pred == 0))
mask

array([False, False, False,  True])

In [125]:
y_true[mask]

array([0])

In [126]:
y_pred[mask]

array([0])

In [64]:
np.where(
    (y_true == 0) & (y_pred == 0), 
    pass, 
    2,
)

SyntaxError: invalid syntax (1416910477.py, line 3)

In [70]:
# filter_zero = y_pred == 0
# filter_true = y_true == 0

filter_eq = (y_pred == y_true) 

np.array([filter_eq])


array([[False, False, False,  True]])

In [83]:
np.array(np.nonzero(y_pred)) & np.array(np.nonzero(y_true))

array([[0, 0]])

In [75]:
y_pred

array([ 0, 11, 10,  0])

In [76]:
np.nonzero(y_true)

(array([0, 1]),)

In [100]:
y_true

array([10, 10,  0,  0])

In [84]:
condition = y_pred == 0
np.extract(condition, y_pred)

array([0, 0])

In [99]:
y_pred

array([ 0, 11, 10,  0])

In [94]:
data = np.array(list((zip(y_pred, y_true))))
data

array([[ 0, 10],
       [11, 10],
       [10,  0],
       [ 0,  0]])

In [95]:
np.where(
    data  == 0,
    99,
    data
)

array([[99, 10],
       [11, 10],
       [10, 99],
       [99, 99]])

array([[ 0, 10],
       [11, 10],
       [10,  0],
       [ 0,  0]])

In [103]:
np.intersect1d(y_pred, y_true, return_indices=True)

(array([ 0, 10]), array([0, 2]), array([2, 0]))

In [105]:
y_pred

array([ 0, 11, 10,  0])